services:
  spire-server:
    image: ghcr.io/spiffe/spire-server:1.5.6
    hostname: spire-server
    volumes:
      - ./spire/server:/opt/spire/conf/server
      - ./bundles:/opt/spire/bundles
    command: ["-config", "/opt/spire/conf/server/server.conf"]
  spire-agent:
    image: ghcr.io/spiffe/spire-agent:1.5.6
    depends_on: ["spire-server"]
    hostname: spire-agent
    volumes:
      - ./spire/agent:/opt/spire/conf/agent
    command: ["-config", "/opt/spire/conf/agent/agent.conf"]
